# Generated by Django 4.0 on 2021-12-22 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_user_has_confirm_confirmstring'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='has_confirm',
            new_name='has_confirmed',
        ),
    ]
